### ISSUE TITLE
Implement update of voting power

### ISSUE THREAD

**Issue by kleinfe** [bloxberg-org/VotingdApp#4]
The voting power of each consortium member is increased/decreased after each voting period according to a batch update:

- If the member voted on all proposals of a voting his voting weight is increased by 1 (25%). The maximum weighting power is 4 (100%). After reaching this threshold the voting power is not incresead anymore

- If the member voted on less than all proposals of a voting his voting power is decreased by 1 (25%), not regarding how many votes he missed in one period. The minimum weighting power is 0 (0%). After reaching this threshold the voting power is not decreased anymore.

**Comment by JamesLawton** [comment]
An alternative to the batch update is a dynamic voting update based on each proposal, which would look something like this:

Calculate the number of proposals in a batch that share the same batch ID:
```
uint proposalsInBatch = 0;
        for (j=1; j<=numProposals;j++){
            if (proposals[proposal].proposalBatch == proposals[j].proposalBatch) {
                proposalsInBatch += 1;
            }
        }
```
Based on how many total proposals in this batch, calculate the dynamicWeight
```
uint precision = 0; //precision is how many decimal places to round, currently it is set to only whole numbers
uint dynamicVoterWeight = uint(100)*(10**precision) / proposalsInBatch; //Calculates a dynamic voting weight based on the total amount of proposals in a batch.
```

Finally, update the current voter weight based on the dynamicWeight for each proposal.


**Advantages**

- For each proposal that a member has voted on, the weight is increased proportionally to the amount in a batch. This means that it's not a winner take all method and is not necessary to vote on every proposal.

- More efficient than the batch sized whole number voting method due to less reliance on additional functions to update the weights, thus costing more gas.

- At the summit, we discussed a similar function to augment the voting weight over time (I believe something that looked like a sine function). This has similar properties to that result, and if I recall correctly the reasoning we landed on the 25, 50% batch update model is to reduce complexity. However, this dynamic batch updating is actually the simpler implementation

**Disadvantages**

- It's likely that people won't have nice, whole numbers depending on the batch size of the proposals. While this isn't strictly a disadvantage, it's worth noting that many members will likely have different weights as more and more votes are cast over time.

- Solidity has difficult handling floating point numbers (it can't as of yet) so it may be necessary to adjust the numbers in the backend. For instance, instead of 1 - 4 voting weight, it would be 100-400. This is just for the smart contract, as the application can be updated to display a more appropriate number or even percentage.
